language: ruby
cache: bundler
matrix:
  fast_finish: true
  include:
  - rvm: 2.1
    env: PUPPET_VERSION="4.3" STRICT_VARIABLES="yes"
    services: docker
    sudo: required
    script: bundle exec rake beaker
  - rvm: 2.1
    env: PUPPET_VERSION="4.5" STRICT_VARIABLES="no"
    services: docker
    sudo: required
    script: bundle exec rake
  - rvm: 2.2
    env: PUPPET_VERSION="4.5" STRICT_VARIABLES="yes"
    services: docker
    sudo: required
    script: bundle exec rake beaker
  - rvm: 2.2
    sudo: required
    script: ruby files/validate_regex.rb
  notifications:
  email:
    recipients:
    - I+2kwgaNPMAzEu2LuJe9u+GIFp5x5JmvTjt7fDhfjMs7Us6+vV5kyQ0YEu+qgZTrVcsccdLkMH7FnXLK2SGnDUFdIBYhb/REIfK1Fs+HmH7Gez7ndqS+wfEJuA76eRY6Is8METF9Ty7I/AmNeg9rqWEgGFGFRYoTikXvsOh5TH86AwIynjaASeq+uYgdS3WWkKJwuZGspOB0o0kY2Ctxvm5IBl58suQ44Xd0TPj9OcsZ/CPbVNbL/Z3k1O+jC5kOXM3G/0dKkJyT5pTrtl89AsiKmKj2fv1mZGi2JxaToXCQSntnefyNcM9bei7sOpcm8XeVO4pe9GhJxxO3rHYTy75L+13Gt6MUHxEbFUcvAxgE4BfVL477BboVPHozacFxPUBO1BcAuRvWaIM+IS4Abys1RA9w0TgmNBx8UIXBqo7qJi5HEjz79OvonDejGTrA/MujVTQaEylygLqUX/NdIC7cFVWfDgZIydemoYBWWYtZLGzFysNQkkd5Jdh5/LA3scZMrisw4JIPmlx93LVOnqZVbgTkYQUxuvBd/o0x9qdwl/NZmuvJbEipgUZLt70afiYBd9wYHWt31nT8EHUhV2Exqrmd/ej54FmqBF3hgBo1bP6OwIzgxpbNzv8AcZPU5v+22P+4UNJlBVDiDzWj4c9Vfj4lLhyhg+BIC5xE05A=
    on_success: never
    on_failure: always
  slack:
    secure: k9X+z4k2IiRQOQ/iSyOpHH/aJ744CNWnqR4qZSAekRTykewDgePOADvVLdmSiqmDrTpvXQslErmiCvxfIsqoQVy9EXW2MZaDOuK3LkHryn5/GnkztEatWtGglVzfQxBstHtmR2+0G4eOsiJBPWKwJMQ4loMJjI6bH5rloGa9ICJf991ZKPAn6/SW8HFrjXc38lquOxTPUDwOfdPnTlFKWCV6wcCpDJno28OTERLg6IUFmrKorWbRmnLnsjq4dpsurIxcV+uKeo69mIAdnjlu1ueyd3QiJAtscYpz0aOtq6mWvq/8tJp1v4nvYN+hw738aryjRNlRirkGVGz/3BKo5yX0ea086R5soxi3JvZYMtN82qu7gwfESFN6Gd4kV8dGh71bi5tcP1HKCESxiC8zo0yfRgS5gLIJWVGF9ayKKfmjkDke00UBACfAGTu5NPg5HHiGMPDYdP/7zM8wcTGn8te8yKNjlV8O2P1pCclxCTkHnjllvSk8XUeB5BMntgfzz/yRG0/cbaZln7Ky9lNepT0k9uYqAqW1/D1iFRRf5l91WpHqRKohz2uCw8wr6+CGKBubkigGx4uAwWMGfqvf7Qxrdcc27GA0jEvssFK/63RVIy9vB4WP6HcxfCjClFmrOCKPuwRT20DDlEcK6FS8vwhpVYjH9ncB3rRqwn0i+dM=
